apiVersion: v1
kind: Secret
metadata:
  name: petclinic-app-secret
  namespace: petclinic
  labels:
    app: spring-petclinic
type: Opaque
data:
  # echo -n 'your-key' | base64
  openai-api-key: UFJPUEVSVEFDS0VZWQ==
