apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: petclinic
  labels:
    app: mysql
    component: database
type: Opaque
data:
  # R00tP@ssw0rd!
  mysql-root-password: UjAwdFBAc3N3MHJkIQ==
  # P3tclin1cP@ss!
  mysql-password: UDN0Y2xpbjFjUEBzcyE=
  # petclinic
  mysql-database: cGV0Y2xpbmljCg==
  # petclinic
  mysql-user: cGV0Y2xpbmljCg==
